package org.voltdb.policysandbox;

/* This file is part of VoltDB.
 * Copyright (C) 2008-2021 VoltDB Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import org.voltdb.types.TimestampType;

/**
 * A class representing a message generated by the server demo
 *
 */
public class PolicyChangeMessage {

    /**
     * A session is identified by sessionId + sessionStartUTC
     */
    private long sessionId;
    
    /**
     * A session is identified by sessionId + sessionStartUTC
     */
    private TimestampType sessionStartUTC;
    
    /**
     * When this event was created on the server. Useful for seeing how long Kafka
     * took to deliver.
     */
    private TimestampType changeTimestamp;
    
    /**
     * Id of 'cell' session is using
     */
    private long cellId;
    
    /**
     * New limit of bandwidth usage per minute
     */
    private int newLimit;

    /**
     * Constructor with data fields - normally we use Kafka.
     * @param cellId
     * @param sessionId
     * @param sessionStartUTC
     * @param changeTimestamp
     * @param newLimit
     */
    public PolicyChangeMessage(long cellId, long sessionId, TimestampType sessionStartUTC,
            TimestampType changeTimestamp, int newLimit) {
        super();
        this.sessionId = sessionId;
        this.sessionStartUTC = sessionStartUTC;
        this.changeTimestamp = changeTimestamp;
        this.cellId = cellId;
        this.newLimit = newLimit;
    }

    /**
     * Constructor for raw Kafka record
     * 
     * @param key
     * @param value
     */
    public PolicyChangeMessage(String key, String value) {
        String[] fields = value.split(",");
        this.sessionId = Long.parseLong(fields[0]);
        this.sessionStartUTC = new TimestampType(fields[1]);
        this.changeTimestamp = new TimestampType(fields[2]);
        this.cellId = Long.parseLong(fields[3]);
        this.newLimit = Integer.parseInt(fields[4]);

    }

    @Override
    public String toString() {

        StringBuilder builder = new StringBuilder();
        builder.append(cellId);
        builder.append(",");
        builder.append(sessionId);
        builder.append(",");
        builder.append(sessionStartUTC);
        builder.append(",");
        builder.append(changeTimestamp);
        builder.append(",");
        builder.append(newLimit);
        return builder.toString();
    }

    /**
     * @return the cellId
     */
    public long getCellId() {
        return cellId;
    }

    /**
     * @return the sessionId
     */
    public long getSessionId() {
        return sessionId;
    }

    /**
     * @return the sessionStartUTC
     */
    public TimestampType getSessionStartUTC() {
        return sessionStartUTC;
    }

    /**
     * @return the recordUsage
     */
    public int getNewLimit() {
        return newLimit;
    }

    /**
     * @return the changeTimestamp
     */
    public TimestampType getChangeTimestamp() {
        return changeTimestamp;
    }

    /**
     * @param changeTimestamp the changeTimestamp to set
     */
    public void setChangeTimestamp(TimestampType changeTimestamp) {
        this.changeTimestamp = changeTimestamp;
    }

}
